### ISSUE TITLE
Use an environment for this key

### ISSUE THREAD

**Issue by zaherg** [ueberdosis/glyphfinder#1]
Hey 

Don't you think that this `masterKey` should be changed to an environment var? and not within the code.

**Comment by hanspagel** [comment]
Yes! We consider to remove the whole license check.

**Comment by zaherg** [comment]
I recommend keeping the license check so that people can learn from it, but remove the key as it should be treated as secret

**Comment by hanspagel** [comment]
Done! Thanks!

**Comment by zaherg** [comment]
@hanspagel you can first delete the file using `git rm --cached src/services/LicenseCheck.js` then re-add the if needed


> --cached
>    Use this option to unstage and remove paths only from the index. Working tree files, whether modified or not, will be left  alone.

https://git-scm.com/docs/git-rm#Documentation/git-rm.txt---cached

**Comment by hanspagel** [comment]
Thanks! I used BFG Repo-Cleaner to remove the history of that file:

`java -jar bfg.jar  --replace-text src/services/LicenseCheck.js`

[1] https://rtyley.github.io/bfg-repo-cleaner/
[2] https://docs.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository#purging-a-file-from-your-repositorys-history
