### ISSUE TITLE
Hide app after copying doesn't work

### ISSUE THREAD

**Issue by mvaneijgen** [ueberdosis/glyphfinder#26]
The window stays open after I copied an emoji

Glyphfinder 1.4.1
macOS 10.15.6 (19G2021)

**Comment by hanspagel** [comment]
Oh! Thanks for the report! Have the same versions of both and can’t reproduce the issue. Will look into it.

**Comment by mvaneijgen** [comment]
Weird, herre is a screens capture. Maybe it helps.
[![-iO6TYEYBsA](https://img.youtube.com/vi/-iO6TYEYBsA/0.jpg)](https://www.youtube.com/watch?v=-iO6TYEYBsA)

**Comment by hanspagel** [comment]
Oh, the „Hide app after copying” option is disabled. Click on the toggle on the right side. When it’s green, it should be enabled and work as expected. Would you mind to try this? Thanks for providing the screen capture!

**Comment by mvaneijgen** [comment]
My bad. I don't know what I was thinking, the toggle somehow confused me, but now that I see it again I can't think of a reason why it did.
