### ISSUE TITLE
Support install via popular package managers

### ISSUE THREAD

**Issue by ev-dev** [ueberdosis/glyphfinder#74]
This tool is great but it the project's discoverability and maintainability (end-user version upgrades) are pretty poor, especially for developers. 

Supporting installation via the most popular package managers would be great for both new users and existing ones. Of course, the prerequisite for all that would be a reliable way to target release/build info. When version info isn't available via git releases, it makes the inclusion of the project in package managers much more peacemeal, but still possible. Many closed source projects do still provide some way to consume release info for inclusion in package managers which need to reliably target some end URL to download.

As far as I can tell there is no simple way to query versions without scraping the project site's Download button target so maybe first step could be some kind of changlelog endpoint, let us know what you think and thanks for the project!

**Comment by hanspagel** [comment]
Thanks for the suggestion, but there’s no update planned at the moment, so I don’t think it’s worth to invest time into making updating easier. ✌️
